"""close-out -- Nightly cash reconciliation, tip split, and waste logging."""

from __future__ import annotations

import re
from datetime import date
from pathlib import Path

from skills._lib import MAYA_ROOT, io, log
from skills._lib.result import Result


_STAFF_TIP_SHARE = 0.80
_HOUSE_TIP_SHARE = 0.20
_VARIANCE_THRESHOLD = 5.0


def _today_str() -> str:
    """Return today's date as YYYY-MM-DD."""
    return date.today().isoformat()


def _parse_waste_items(raw: str | None) -> list[dict]:
    """Parse waste items from 'item1:qty1,item2:qty2' format.

    Returns list of dicts with 'item' and 'qty' keys.
    Raises ValueError if format is invalid.
    """
    if not raw or not raw.strip():
        return []
    items = []
    for token in raw.split(","):
        token = token.strip()
        if not token:
            continue
        parts = token.split(":")
        if len(parts) != 2:
            raise ValueError(
                "Invalid waste item format: {token}. Expected 'name:number'.".format(
                    token=token
                )
            )
        name = parts[0].strip()
        try:
            qty = float(parts[1].strip())
        except ValueError:
            raise ValueError(
                "Invalid quantity in waste item: {token}".format(token=token)
            )
        items.append({"item": name, "qty": qty})
    return items


def _build_reconciliation_md(
    date_str: str,
    cash_count: float,
    card_total: float,
    expected: float,
    variance: float,
    tip_total: float,
    staff_tips: float,
    house_tips: float,
    waste_items: list[dict],
) -> str:
    """Build the markdown reconciliation report."""
    lines = [
        "# Close-Out: {date}".format(date=date_str),
        "",
        "## Revenue",
        "",
        "| Source | Amount |",
        "|--------|--------|",
        "| Cash | ${cash:.2f} |".format(cash=cash_count),
        "| Card | ${card:.2f} |".format(card=card_total),
        "| **Total** | **${total:.2f}** |".format(total=cash_count + card_total),
        "| Expected | ${expected:.2f} |".format(expected=expected),
        "| **Variance** | **${variance:+.2f}** |".format(variance=variance),
        "",
        "## Tips",
        "",
        "| Split | Amount |",
        "|-------|--------|",
        "| Total tips | ${total:.2f} |".format(total=tip_total),
        "| Staff (80%) | ${staff:.2f} |".format(staff=staff_tips),
        "| House (20%) | ${house:.2f} |".format(house=house_tips),
        "",
    ]

    if waste_items:
        lines.extend([
            "## Waste",
            "",
            "| Item | Qty |",
            "|------|-----|",
        ])
        for w in waste_items:
            lines.append(
                "| {item} | {qty} |".format(item=w["item"], qty=w["qty"])
            )
        lines.append("")

    lines.append("---")
    lines.append("Generated by Maya close-out skill.")
    lines.append("")
    return "\n".join(lines)


def run(ctx: object) -> Result:
    """Main skill entry point."""
    log.event("close_out.started")

    args = ctx.args
    date_str = args.date or _today_str()

    # Validate date format
    if args.date and not re.match(r"^\d{4}-\d{2}-\d{2}$", args.date):
        log.event("close_out.invalid_date", date=args.date)
        return {
            "skill": "close-out",
            "status": "fail",
            "summary": "Invalid --date format: {d}. Expected YYYY-MM-DD.".format(d=args.date),
            "data": {},
            "findings": [],
            "metrics": {},
        }

    # Validate required args
    missing = []
    if args.cash_count is None:
        missing.append("--cash-count")
    if args.card_total is None:
        missing.append("--card-total")
    if args.expected is None:
        missing.append("--expected")

    if missing:
        summary = "Missing required arguments: {args}".format(
            args=", ".join(missing)
        )
        log.event("close_out.missing_args", count=len(missing))
        return {
            "skill": "close-out",
            "status": "fail",
            "summary": summary,
            "data": {},
            "findings": [],
            "metrics": {},
        }

    cash_count = args.cash_count
    card_total = args.card_total
    expected = args.expected
    tip_total = args.tip_total or 0.0

    # Parse waste items
    try:
        waste_items = _parse_waste_items(args.waste_items)
    except ValueError as exc:
        log.event("close_out.waste_parse_error")
        return {
            "skill": "close-out",
            "status": "fail",
            "summary": str(exc),
            "data": {},
            "findings": [],
            "metrics": {},
        }

    # Calculate variance
    actual_total = cash_count + card_total
    variance = actual_total - expected

    # Split tips (house = remainder to avoid rounding gap)
    staff_tips = round(tip_total * _STAFF_TIP_SHARE, 2)
    house_tips = round(tip_total - staff_tips, 2)

    # Build findings
    findings = []

    if variance > _VARIANCE_THRESHOLD:
        findings.append({
            "severity": "warn",
            "code": "CASH_OVER",
            "subject": date_str,
            "message": "Cash over by ${v:.2f} (threshold: ${t:.2f}).".format(
                v=variance, t=_VARIANCE_THRESHOLD
            ),
        })
    elif variance < -_VARIANCE_THRESHOLD:
        findings.append({
            "severity": "warn",
            "code": "CASH_SHORT",
            "subject": date_str,
            "message": "Cash short by ${v:.2f} (threshold: ${t:.2f}).".format(
                v=abs(variance), t=_VARIANCE_THRESHOLD
            ),
        })

    if tip_total > 0:
        findings.append({
            "severity": "info",
            "code": "TIPS_SPLIT",
            "subject": date_str,
            "message": "Tips ${total:.2f} split: staff ${staff:.2f}, house ${house:.2f}.".format(
                total=tip_total, staff=staff_tips, house=house_tips
            ),
        })

    if waste_items:
        waste_summary = ", ".join(
            "{item}:{qty}".format(item=w["item"], qty=w["qty"])
            for w in waste_items
        )
        findings.append({
            "severity": "info",
            "code": "WASTE_LOGGED",
            "subject": date_str,
            "message": "Waste logged: {items}.".format(items=waste_summary),
        })

    # Write reconciliation file
    output_dir_arg = args.data_dir
    if output_dir_arg:
        output_dir = Path(output_dir_arg)
    else:
        output_dir = MAYA_ROOT / "data" / "close-out"

    # Allowlist root is always MAYA_ROOT — prevents --data-dir escape
    allowlist_root = MAYA_ROOT

    output_path = output_dir / "{date}.md".format(date=date_str)

    # Overwrite guard: refuse to clobber existing close-out unless --force
    force = getattr(args, "force", False)
    if not force and output_path.exists():
        log.event("close_out.exists", date=date_str)
        return {
            "skill": "close-out",
            "status": "fail",
            "summary": "Close-out for {d} already exists. Use --force to overwrite.".format(d=date_str),
            "data": {"output_file": str(output_path)},
            "findings": [],
            "metrics": {},
        }

    content = _build_reconciliation_md(
        date_str=date_str,
        cash_count=cash_count,
        card_total=card_total,
        expected=expected,
        variance=variance,
        tip_total=tip_total,
        staff_tips=staff_tips,
        house_tips=house_tips,
        waste_items=waste_items,
    )

    io.atomic_write_text(output_path, content, allowlist_root=allowlist_root)
    log.event("close_out.file_written", date=date_str)

    status = "warn" if any(f["severity"] == "warn" for f in findings) else "ok"
    summary = "Close-out {date}: actual ${actual:.2f}, expected ${expected:.2f}, variance ${variance:+.2f}.".format(
        date=date_str, actual=actual_total, expected=expected, variance=variance
    )

    data = {
        "date": date_str,
        "cash_count": cash_count,
        "card_total": card_total,
        "actual_total": actual_total,
        "expected": expected,
        "variance": variance,
        "tip_total": tip_total,
        "staff_tips": staff_tips,
        "house_tips": house_tips,
        "waste_items": waste_items,
        "output_file": str(output_path),
    }

    log.event(
        "close_out.finished",
        status=status,
        findings_count=len(findings),
    )

    return {
        "skill": "close-out",
        "status": status,
        "summary": summary,
        "data": data,
        "findings": findings,
        "metrics": {},
    }
